var data = {
    'restaurantes' : [
        {
            'adress' : 'Acueducto #5098 Xochimilco, CDMX',
            'name' : 'El Rinconcito',
            'food' : 'Mexicana',
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : true,
            'special-food' : 'Tacos',
        },
        {
            'adress' : 'Halcon #4059 Xochimilco, CDMX',
            'name' : 'La Chilanguita',
            'food' : 'Mexicana',
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : false,
            'special-food' : 'Pozole',
        },
        {
            'adress' : 'Eje central #541 Narvarte Poniente, CDMX',
            'name' : 'Pedro Navajas',
            'food' : 'Mexicana',
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : true,
            'special-food' : 'Enchiladas con rabano',
        },
        {
            'adress' : 'Tonalá #30 Roma Norte, CDMX',
            'name' : 'Restaurante Laboratoria',
            'food' : 'Mexicana',
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : false,
            'special-food' : 'Niñas envueltas',
        },
        {
            'adress' : 'Tlalpan #4 Lo Volcanes, CDMX',
            'name' : 'Silvana',
            'food' : 'Mexicana',
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : false,
            'special-food' : 'Chiles Rellenos',
        },
        {
            'adress' : '',
            'name' : '',
            'food' : '', 
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : true,
            'special-food' : '',
        },
        {
            'adress' : '',
            'name' : '',
            'food' : '', 
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : true,
            'special-food' : '',
        },
        {
            'adress' : '',
            'name' : '',
            'food' : '', 
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : false,
            'special-food' : '',
        },
        {
            'adress' : '',
            'name' : '',
            'food' : '', 
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : true,
            'special-food' : '',
        },
        {
            'adress' : '',
            'name' : '',
            'food' : '', 
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : false,
            'special-food' : '',
        },
        {
            'adress' : '',
            'name' : '',
            'food' : '', 
            'photo' : 'http://dummyimage.com/162x148.png/ff4444/ffffff',
            'service' : false,
            'special-food' : '',
        }
    ]
};
console.log(data);